[deps]
CIndices = "5a98b6c4-18fa-405d-92b3-8277d93fed36"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Finch = "9177782c-1635-4eb9-9bfb-d9dfa25e6bce"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
